name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: 'Create env file'
        run: |
          touch .env
          echo REACT_APP_ONFARM_OLD_API_USERNAME=${{ secrets.REACT_APP_ONFARM_OLD_API_USERNAME }} >> .env
          echo REACT_APP_ONFARM_OLD_API_PASSWORD=${{ secrets.REACT_APP_ONFARM_OLD_API_PASSWORD }} >> .env
          echo REACT_APP_ONFARM_DEV_API_URL=${{ secrets.REACT_APP_ONFARM_DEV_API_URL }} >> .env
          echo REACT_APP_ONFARM_PROD_API_URL=${{ secrets.REACT_APP_ONFARM_PROD_API_URL }} >> .env
          echo REACT_APP_ONFARM_OLD_API_URL=${{ secrets.REACT_APP_ONFARM_OLD_API_URL }} >> .env
          echo REACT_APP_HOLOGRAM_WATER_SENSOR_API_KEY=${{ secrets.REACT_APP_HOLOGRAM_WATER_SENSOR_API_KEY }} >> .env
          echo REACT_APP_HOLOGRAM_STRESS_CAM_API_KEY=${{ secrets.REACT_APP_HOLOGRAM_STRESS_CAM_API_KEY }} >> .env
          echo REACT_APP_CONTACT_PERSON_NAME=${{ secrets.REACT_APP_CONTACT_PERSON_NAME }} >> .env
          echo REACT_APP_CONTACT_PERSON_EMAIL=${{ secrets.REACT_APP_CONTACT_PERSON_EMAIL }} >> .env
          echo REACT_APP_DEVELOPER_CONTACT_NAME=${{ secrets.REACT_APP_DEVELOPER_CONTACT_NAME }} >> .env
          echo REACT_APP_DEVELOPER_CONTACT_EMAIL=${{ secrets.REACT_APP_DEVELOPER_CONTACT_EMAIL }} >> .env
          echo REACT_APP_GOOGLE_API_KEY_PROD=${{ secrets.REACT_APP_GOOGLE_API_KEY_PROD }} >> .env
          echo REACT_APP_GOOGLE_API_KEY_DEV=${{ secrets.REACT_APP_GOOGLE_API_KEY_DEV }} >> .env
          echo REACT_APP_GITHUB_AUTH_TOKEN=${{ secrets.REACT_APP_GITHUB_AUTH_TOKEN }} >> .env
          echo REACT_APP_ONFARM_GLOBAL_API_KEY=${{ secrets.REACT_APP_ONFARM_GLOBAL_API_KEY }} >> .env
          cat .env
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DUNE_045CC160F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DUNE_045CC160F }}
          action: "close"
